### ISSUE TITLE
Assembler: Register operands interpret immediates as register Xn 

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#12]
Any of the register (i.e. not immediate) instructions parse an operand as register number Xn, even if the register letter is omitted, rather than raising an error such as 'invalid register'.

For example `AND A0,A1,10` assembles as `AND A0,A1,X10` (i.e. `AND A0,A1,A0`) rather than complaining `10` isn't a valid register name.  The number could appear as RD or RS1 or RS2.

I'm not sure if you regard this as a bug or not (maybe it's correct behaviour), but it's certainly caught me out a few times where I've meant to use `ANDI` (or similar).  Unless it's specifically required, I think it would best generating an error.

**Comment by hoglet67** [comment]
This is currently intentional, because I was following the same general pattern used in Richard's ARM 32 assembler, which has this same fallback behaviour:
https://github.com/hoglet67/BBCSDL/blob/master/src/bbasmb_arm_32.c#L136

You can see here if the lookup of the register name failed, then it's parsed as a number instead,

I've also been caught out by this, so I tend to agree with you that it might be best to change it.

The  thing we would loose would be the ability to have a FOR loop where the variable was used as the register. e.g. generating code to push all register onto the stack

```
DIM code% 1000
FOR I% = 0 TO 3 STEP 3
P%=code%
[OPT I%
.test
ADDI sp, sp, -128
]
FOR rs = 0 TO 31
[OPT I%
SW rs, (4*rs)(sp)
]
NEXT
:
REM Do something with the registers
:
FOR rd = 0 TO 31
[OPT I%
LW rd, (4*rd)(sp)
]
NEXT
[OPT I%
ADDI sp, sp, 128
RET
]
NEXT
CALL test
```

Dave

**Comment by mincebert** [comment]
Yes — I can see how that would be useful as there's no equivalent of LDRM/STRM.

Could it be restricted to requiring a prefix such as `X#` — e.g. in your above example `SW X#rs, (4*rs)(sp)`?  Then you would have to make it explicit you wanted it to do something clever!

**Comment by hoglet67** [comment]
Let me have a think about this....

**Comment by hoglet67** [comment]
I've adopted your suggestion of using the x# prefix.
