### ISSUE TITLE
ESCAPE not being cleared on BREAK

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#16]
Another Escape clearing bug!  If you push ESCAPE somewhere that it won't be handled and then push BREAK, you're dropped back into RVBASIC but whatever command you type (e.g. `OLD`) will print `Escape` when you push RETURN and not be executed.

For example, in my case, I've assembled some RISC-V code using the BASIC assembler and have `CALL`ed it and it runs.  My code doesn't, however, check for nor handle ESCAPE, so pushing it does nothing and the machine code continues running.  But, after pushing BREAK, I get the spurious `Escape` after the first command back in RVBASIC.

This is similar to bug #15.

**Comment by mincebert** [comment]
I suppose this could be a PiTubeDirect copro bug - I haven’t seen what happens if you do this outside RVBASIC.  You’ll know better than me, though!

**Comment by hoglet67** [comment]
The case you reported was BBC Basic, but there may well be a similar issue in the tube ROM itself, as I don't think the workspace (inc the default escape flag) is cleared on reset. I'll investigate with the debugger,

**Comment by mincebert** [comment]
I just tried running the code from the `*` prompt directly (i.e. not in RVBASIC) and didn't get the same behaviour there (i.e. running commands after BREAK didn't do a spurious `Escape`).

**Comment by hoglet67** [comment]
I think there is a latent bug in the RISC-V Tube ROM, because it doesn't clear the escape flag on BREAK. It's not causing an error because nothing is currently reading it directly.

The escape flag is a bit unusual. On the 6502 Co Pro it's in a well known location (&FF) and it's effectively part of the MOS API, i.e. languages are allowed to check it directly. I think this is for efficiency.

On the RISC-V Tube ROM the escape flag is at a different address (&FBFE00), so I'm not sure we want programs to be hard-coded with that.

In JGH's PDP11 Co Pro docs, he gives various ways of checking for escape. See the section titled "Escape state" [here](https://mdfs.net/Docs/Books/PDP11CoPro/Technical). It's possible to use OS_HANDLERS to ask for the address of the escape flag, or even change it. That also works the same on RISC-V.

Anyway, this does I think need clearing as well on BREAK. So I'll add that code as well.
